### PR TITLE
Update hodl.c

### PR DESCRIPTION
**Pull request by Qwertylex**
I had an issue: 
hodl.c: In function ‘scanhash_hodl’:
hodl.c:67:20: error: storage size of ‘ctx’ isn’t known
     EVP_CIPHER_CTX ctx;
                    ^~~
but this PR fixes it, unless I did something wrong... however it segfaults after a few seconds of benchmarking?

### CODE REVIEW

**Comment by bitbandi** [comment]
not good, this is just change the pointer usage.
the error "storage size of isn’t known" means, that EVP_CIPHER_CTX struct is unknown. maybe you use too old or too new openssl version.

**Comment by Qwertylex** [comment]
yes, I have openssl 1.1.0.f-2
https://www.archlinux.org/packages/core/x86_64/openssl/

...shouldn't you update your code to work with 1.1.0?
Maybe I don't know how to do that properly, sorry.
